export enum ADDITIONAL_EXTENSIONS {
  PAGE_EMBED_COMPONENT = "pageEmbedComponent",
  COLLABORATION_CARET = "collaborationCursor",
  ATTACHMENT = "attachmentComponent",
  COMMENTS = "commentMark",
  MATHEMATICS = "mathematics",
  INLINE_MATH = "inlineMath",
  BLOCK_MATH = "blockMath",
  EXTERNAL_EMBED = "externalEmbedComponent",
  PAGE_LINK_COMPONENT = "pageLinkComponent",
  DRAWIO = "drawIoComponent",
  NODE_HIGHLIGHT = "nodeHighlight",
}

export const ADDITIONAL_BLOCK_NODE_TYPES = [
  ADDITIONAL_EXTENSIONS.PAGE_EMBED_COMPONENT,
  ADDITIONAL_EXTENSIONS.ATTACHMENT,
  ADDITIONAL_EXTENSIONS.BLOCK_MATH,
  ADDITIONAL_EXTENSIONS.EXTERNAL_EMBED,
  ADDITIONAL_EXTENSIONS.PAGE_LINK_COMPONENT,
  ADDITIONAL_EXTENSIONS.DRAWIO,
];
