# Generated by Django 4.2.27 on 2026-01-13 09:46

from django.db import migrations, models
import plane.db.models.workspace


def get_default_checklist():
    return {
        "project_created": True,
        "project_joined": True,
        "work_item_created": True,
        "team_members_invited": True,
        "page_created": True,
        "ai_chat_tried": True,
        "integration_linked": True,
        "view_created": True,
        "sticky_created": True,
    }


def get_default_explored_features():
    return {"github_integrated": True, "slack_integrated": True, "ai_chat_tried": True}


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0115_auto_20260105_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemember',
            name='explored_features',
            field=models.JSONField(default=get_default_explored_features),
        ),
        migrations.AlterField(
            model_name='workspacemember',
            name='explored_features',
            field=models.JSONField(default=plane.db.models.workspace.get_default_explored_features),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='getting_started_checklist',
            field=models.JSONField(default=get_default_checklist),
        ),
        migrations.AlterField(
            model_name='workspacemember',
            name='getting_started_checklist',
            field=models.JSONField(default=plane.db.models.workspace.get_default_checklist),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='tips',
            field=models.JSONField(default=plane.db.models.workspace.get_default_tips),
        ),
        migrations.AddField(
            model_name='profile',
            name='notification_view_mode',
            field=models.CharField(choices=[('full', 'Full'), ('compact', 'Compact')], default='full', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='is_password_reset_required',
            field=models.BooleanField(default=False),
        ),
    ]
