# Generated by Django 4.2.22 on 2025-10-01 12:17

from django.db import migrations, models


def populate_application_fields(apps, schema_editor):
    """
    Populate new fields for existing Application instances with default values.
    """
    Application = apps.get_model('authentication', 'Application')
    
    # Default values based on the model and mock data
    default_status = "draft"
    
    # Update all existing applications
    for app in Application.objects.all():
        if app.status == 'draft':  # Only update if still draft
            # Set published apps to 'published', others remain 'draft'
            if app.published_at is not None:
                app.status = "published"
            else:
                app.status = default_status
        
        app.save()


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_accesstoken_workspace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='application',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(default='draft', max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='supported_environments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='application',
            name='supported_plans',
            field=models.JSONField(blank=True, default=list),
        ),
        # Data migration to populate existing rows
        migrations.RunPython(
            populate_application_fields,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
