# Generated by Django 4.2.22 on 2025-10-10 09:49

from django.db import migrations, models
from django.utils.text import slugify


def update_existing_slugs(apps, schema_editor):
    ApplicationCategory = apps.get_model('authentication', 'ApplicationCategory')
    for category in ApplicationCategory.objects.all():
        category.slug = slugify(category.name)
        category.save()

class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_application_links_application_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=48, null=True, unique=True),
        ),
        migrations.RunPython(update_existing_slugs, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='applicationcategory',
            name='slug',
            field=models.SlugField(max_length=48, unique=True)
        ),
    ]
