# Generated by Django 4.2.24 on 2025-10-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_applicationcategory_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ('-published_at',), 'verbose_name': 'Application', 'verbose_name_plural': 'Applications'},
        ),
        migrations.RemoveField(
            model_name='application',
            name='priority',
        ),
        migrations.AddField(
            model_name='application',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='applicationcategory',
            name='sort_order',
            field=models.FloatField(default=65535.0),
        ),
        migrations.AlterModelOptions(
            name='applicationcategory',
            options={'ordering': ('sort_order', '-created_at'), 'verbose_name': 'Application Category', 'verbose_name_plural': 'Application Categories'},
        ),
        
        
    ]
