# Generated by Django 4.2.22 on 2025-10-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='webhook_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
