# Generated by Django 4.2.27 on 2025-12-30 08:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import plane.authentication.models.oauth
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0112_auto_20251124_0603'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0013_application_webhook_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('domain', models.CharField(db_index=True, max_length=255, validators=[django.core.validators.RegexValidator(message='Enter a valid domain name', regex='^(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\\.)+[a-zA-Z]{2,}$')])),
                ('verification_token', models.CharField(max_length=255, unique=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('pending', 'pending'), ('verified', 'verified'), ('failed', 'failed')], default='pending', max_length=255)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
                'db_table': 'domains',
            },
        ),
        migrations.CreateModel(
            name='IdentityProvider',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('client_id', models.TextField(blank=True, null=True)),
                ('client_secret', models.TextField(blank=True, null=True)),
                ('authorize_url', models.TextField(blank=True, null=True)),
                ('token_url', models.TextField(blank=True, null=True)),
                ('userinfo_url', models.TextField(blank=True, null=True)),
                ('logout_url', models.TextField(blank=True, null=True)),
                ('entity_id', models.TextField(blank=True, null=True)),
                ('sso_url', models.TextField(blank=True, null=True)),
                ('slo_url', models.TextField(blank=True, null=True)),
                ('certificate', models.TextField(blank=True, null=True)),
                ('provider', models.CharField(choices=[('saml', 'SAML'), ('oidc', 'OIDC')], max_length=255)),
                ('is_enabled', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_providers', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Identity Provider',
                'verbose_name_plural': 'Identity Providers',
                'db_table': 'identity_providers',
            },
        ),
        migrations.AlterField(
            model_name='application',
            name='slug',
            field=models.SlugField(max_length=48, unique=True, validators=[plane.authentication.models.oauth.custom_app_slug_validator]),
        ),
        migrations.CreateModel(
            name='IdentityProviderDomain',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_domains', to='authentication.domain')),
                ('identity_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_domains', to='authentication.identityprovider')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Identity Provider Domain',
                'verbose_name_plural': 'Identity Provider Domains',
                'db_table': 'identity_provider_domains',
            },
        ),
        migrations.AddConstraint(
            model_name='identityproviderdomain',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('identity_provider', 'domain'), name='identity_provider_domain_unique_identity_provider_domain_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='identityproviderdomain',
            unique_together={('identity_provider', 'domain')},
        ),
        migrations.AddConstraint(
            model_name='identityprovider',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'provider'), name='identity_provider_unique_workspace_provider_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='identityprovider',
            unique_together={('workspace', 'provider')},
        ),
        migrations.AddConstraint(
            model_name='domain',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('verification_status', 'verified')), fields=('domain',), name='unique_verified_domain_when_not_deleted'),
        ),
        migrations.AddConstraint(
            model_name='domain',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'domain'), name='unique_workspace_domain_when_not_deleted'),
        ),
    ]
