# Generated by Django 4.2.27 on 2025-01-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_domain_identityprovider_alter_application_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityprovider',
            name='disable_requested_authn_context',
            field=models.BooleanField(default=True),
        ),
    ]
