export type TExtensions =
  | "ai"
  | "collaboration-caret"
  | "issue-embed"
  | "page-embed"
  | "slash-commands"
  | "enter-key"
  | "image"
  | "nested-pages"
  | "external-embed"
  | "attachments"
  | "video-attachments"
  | "comments"
  | "mathematics"
  | "drawio"
  | "copy-block-link"
  | "selection-conversion";
