# Generated by Django 4.2.26 on 2025-11-24 15:02

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
from django.utils.text import slugify
import uuid


def rename_issue_properties_to_maintain_uniqueness(apps, schema_editor):
    IssueProperty = apps.get_model('ee', 'IssueProperty')
    BATCH_SIZE = 1000
    issue_properties = []
    
    for issue_property in IssueProperty.objects.all().select_related('project', 'issue_type'):
        # The name change should be appended with the project identifier and issue type name
        issue_property.name = slugify("{}_{}_{}".format(
            issue_property.display_name,
            issue_property.project.identifier if issue_property.project else '',
            issue_property.issue_type.name if issue_property.issue_type else '',
        ))
        issue_properties.append(issue_property)
        
        if len(issue_properties) >= BATCH_SIZE:
            IssueProperty.objects.bulk_update(issue_properties, ['name'])
            issue_properties = []

    if issue_properties:
        IssueProperty.objects.bulk_update(issue_properties, ['name'])

def reverse_rename_issue_properties(apps, schema_editor):
    IssueProperty = apps.get_model('ee', 'IssueProperty')
    BATCH_SIZE = 1000
    issue_properties = []
    
    for issue_property in IssueProperty.objects.all():
        issue_property.name = slugify(issue_property.display_name)
        issue_properties.append(issue_property)
        
        if len(issue_properties) >= BATCH_SIZE:
            IssueProperty.objects.bulk_update(issue_properties, ['name'])
            issue_properties = []

    if issue_properties:
        IssueProperty.objects.bulk_update(issue_properties, ['name'])


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0111_notification_notif_receiver_status_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ee', '0056_alter_workspacememberactivitymodel_workspace_member'),
    ]

    operations = [
        migrations.RunPython(rename_issue_properties_to_maintain_uniqueness, reverse_code=reverse_rename_issue_properties),
        migrations.CreateModel(
            name='IssueTypeProperty',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_required', models.BooleanField(default=False)),
                ('default_value', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.FloatField(default=65535)),
                ('external_source', models.CharField(blank=True, max_length=255, null=True)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'issue_type_properties',
                'ordering': ['sort_order'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='issueproperty',
            name='issue_property_unique_name_project_when_deleted_at_null',
        ),
        migrations.AlterUniqueTogether(
            name='issueproperty',
            unique_together={('workspace', 'name', 'deleted_at')},
        ),
        migrations.AlterField(
            model_name='issueproperty',
            name='issue_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='db.issuetype'),
        ),
        migrations.AddConstraint(
            model_name='issueproperty',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'name'), name='issue_property_unique_name_workspace_when_deleted_at_null'),
        ),
        migrations.AddField(
            model_name='issuetypeproperty',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='issuetypeproperty',
            name='issue_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_type_properties', to='db.issuetype'),
        ),
        migrations.AddField(
            model_name='issuetypeproperty',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project'),
        ),
        migrations.AddField(
            model_name='issuetypeproperty',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_type_properties', to='ee.issueproperty'),
        ),
        migrations.AddField(
            model_name='issuetypeproperty',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='issuetypeproperty',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace'),
        ),
        migrations.AddConstraint(
            model_name='issuetypeproperty',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('issue_type', 'property'), name='issue_type_property_unique_issue_type_property_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='issuetypeproperty',
            unique_together={('issue_type', 'property', 'deleted_at')},
        ),
    ]
