# Generated by Django 4.2.27 on 2026-01-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ee', '0057_issuetypeproperty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttemplate',
            name='is_milestone_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
