# Generated by Django 4.2.22 on 2026-01-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ee", "0059_rename_projectmemberactivitymodel_projectmemberactivity_and_more"),
    ]

    operations = [
        # Add interval_count field for custom intervals (every X days/weeks/months/years)
        migrations.AddField(
            model_name="recurringworkitemtask",
            name="interval_count",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Repeat every X intervals (e.g., 2 = every 2 weeks/months)",
            ),
        ),
        # Next scheduled execution time (calendar-accurate)
        migrations.AddField(
            model_name="recurringworkitemtask",
            name="next_scheduled_at",
            field=models.DateTimeField(
                null=True,
                blank=True,
                help_text="Next scheduled execution time (calendar-accurate)",
            ),
        ),
        # Last successful execution time
        migrations.AddField(
            model_name="recurringworkitemtask",
            name="last_run_at",
            field=models.DateTimeField(
                null=True,
                blank=True,
                help_text="Last successful execution time",
            ),
        ),
        # Index for efficient batch scheduler queries
        migrations.AddIndex(
            model_name="recurringworkitemtask",
            index=models.Index(
                fields=["enabled", "next_scheduled_at"],
                name="rwt_enabled_next_idx",
            ),
        ),
        # Increase task_id field size to accommodate longer task IDs
        # Format: recurring_{uuid}_{timestamp} = ~57 characters
        migrations.AlterField(
            model_name="recurringworkitemtasklog",
            name="task_id",
            field=models.CharField(
                max_length=255,
                help_text="Unique per Celery execution",
            ),
        ),
    ]
