# Generated by Django 4.2.25 on 2026-02-04 10:00

from django.db import migrations


def migrate_deploy_board_to_intake_email(apps, schema_editor):
    """
    Migrate intake email entries from DeployBoard to IntakeEmail model.
    """
    DeployBoard = apps.get_model("db", "DeployBoard")
    IntakeEmail = apps.get_model("ee", "IntakeEmail")

    # Get all DeployBoard entries where entity_name is "intake_email"
    deploy_board_intake_emails = DeployBoard.objects.filter(
        entity_name="intake_email"
    ).select_related("intake")

    intake_emails_to_create = []
    for db_entry in deploy_board_intake_emails:
        if db_entry.intake:
            intake_emails_to_create.append(
                IntakeEmail(
                    intake_id=db_entry.intake_id,
                    project_id=db_entry.intake.project_id,
                    workspace_id=db_entry.workspace_id,
                    anchor=db_entry.anchor,
                    is_disabled=db_entry.is_disabled,
                    created_at=db_entry.created_at,
                    updated_at=db_entry.updated_at,
                    created_by_id=db_entry.created_by_id,
                    updated_by_id=db_entry.updated_by_id,
                    deleted_at=db_entry.deleted_at,
                )
            )

    if intake_emails_to_create:
        IntakeEmail.objects.bulk_create(intake_emails_to_create, batch_size=1000)

    # Delete migrated DeployBoard entries
    deploy_board_intake_emails.delete()


def reverse_migrate_intake_email_to_deploy_board(apps, schema_editor):
    """
    Reverse migration: Move IntakeEmail data back to DeployBoard.
    """
    DeployBoard = apps.get_model("db", "DeployBoard")
    IntakeEmail = apps.get_model("ee", "IntakeEmail")

    intake_emails = IntakeEmail.objects.all().select_related("intake")

    deploy_boards_to_create = []
    for intake_email in intake_emails:
        if intake_email.intake:
            deploy_boards_to_create.append(
                DeployBoard(
                    entity_identifier=intake_email.intake_id,
                    entity_name="intake_email",
                    workspace_id=intake_email.workspace_id,
                    intake_id=intake_email.intake_id,
                    anchor=intake_email.anchor,
                    is_disabled=intake_email.is_disabled,
                    created_at=intake_email.created_at,
                    updated_at=intake_email.updated_at,
                    created_by_id=intake_email.created_by_id,
                    updated_by_id=intake_email.updated_by_id,
                    deleted_at=intake_email.deleted_at,
                )
            )

    if deploy_boards_to_create:
        DeployBoard.objects.bulk_create(deploy_boards_to_create, batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ("ee", "0063_intakeemail"),
    ]

    operations = [
        migrations.RunPython(
            migrate_deploy_board_to_intake_email,
            reverse_code=reverse_migrate_intake_email_to_deploy_board,
        ),
    ]
