from typing import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0b378a3ddb8e"
down_revision: Union[str, None] = "f395eac7eb26"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "action_artifacts",
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("entity", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("action", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_executed", sa.Boolean(), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=True),
        sa.Column("chat_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.id"], name="fk_action_artifacts_chat_id"),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], name="fk_action_artifacts_message_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_action_artifacts_chat_id"), "action_artifacts", ["chat_id"], unique=False)
    op.create_index(op.f("ix_action_artifacts_id"), "action_artifacts", ["id"], unique=False)
    op.create_index(op.f("ix_action_artifacts_message_id"), "action_artifacts", ["message_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_action_artifacts_message_id"), table_name="action_artifacts")
    op.drop_index(op.f("ix_action_artifacts_id"), table_name="action_artifacts")
    op.drop_index(op.f("ix_action_artifacts_chat_id"), table_name="action_artifacts")
    op.drop_table("action_artifacts")
    # ### end Alembic commands ###
