from typing import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2a2367c71b4d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_artifacts",
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("agent_name", sa.Enum("PRD_WRITER", name="agentstype"), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=True),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("issue_id", sa.Uuid(), nullable=True),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content_type", sa.Enum("MARKDOWN", name="agentartifactcontenttype"), nullable=False),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agent_artifacts_id"), "agent_artifacts", ["id"], unique=False)
    op.create_table(
        "chats",
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("icon", sa.JSON(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chats_id"), "chats", ["id"], unique=False)
    op.create_index(op.f("ix_chats_user_id"), "chats", ["user_id"], unique=False)
    op.create_table(
        "github_webhooks",
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("commit_id", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("branch_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("processed", sa.Boolean(), nullable=False),
        sa.Column("files_processed", sa.Integer(), nullable=True),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_github_webhooks_id"), "github_webhooks", ["id"], unique=False)
    op.create_table(
        "llm_models",
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("model_key", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("max_tokens", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("model_key"),
    )
    op.create_index(op.f("ix_llm_models_id"), "llm_models", ["id"], unique=False)
    op.create_table(
        "llm_model_pricing",
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("llm_model_id", sa.UUID(), nullable=True),
        sa.Column("text_input_price", sa.Float(), nullable=True),
        sa.Column("text_output_price", sa.Float(), nullable=True),
        sa.Column("cached_text_input_price", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["llm_model_id"], ["llm_models.id"], name="fk_llm_model_pricing_llm_model_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_llm_model_pricing_id"), "llm_model_pricing", ["id"], unique=False)
    op.create_table(
        "messages",
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("reasoning", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("user_type", sa.Enum("USER", "ASSISTANT", "SYSTEM", name="usertypechoices"), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("relates_to", sa.UUID(), nullable=True),
        sa.Column("llm_model_id", sa.UUID(), nullable=True),
        sa.Column("chat_id", sa.UUID(), nullable=True),
        sa.Column("llm_model", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.id"], name="fk_messages_chat_id"),
        sa.ForeignKeyConstraint(["llm_model"], ["llm_models.model_key"], name="fk_messages_llm_model"),
        sa.ForeignKeyConstraint(["llm_model_id"], ["llm_models.id"], name="fk_messages_llm_model_id"),
        sa.ForeignKeyConstraint(["parent_id"], ["messages.id"], name="fk_messages_parent_id"),
        sa.ForeignKeyConstraint(["relates_to"], ["messages.id"], name="fk_messages_relates_to"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_messages_chat_id"), "messages", ["chat_id"], unique=False)
    op.create_index(op.f("ix_messages_id"), "messages", ["id"], unique=False)
    op.create_index(op.f("ix_messages_sequence"), "messages", ["sequence"], unique=False)
    op.create_table(
        "message_feedbacks",
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.Enum("FEEDBACK", "REACTION", name="messagefeedbacktypechoices"), nullable=False),
        sa.Column("feedback", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("reaction", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("feedback_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], name="fk_message_feedbacks_message_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_message_feedbacks_id"), "message_feedbacks", ["id"], unique=False)
    op.create_index(op.f("ix_message_feedbacks_user_id"), "message_feedbacks", ["user_id"], unique=False)
    op.create_table(
        "message_flow_steps",
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("step_order", sa.Integer(), nullable=False),
        sa.Column("step_type", sa.Enum("REWRITE", "ROUTING", "TOOL", "COMBINATION", name="flowsteptype"), nullable=False),
        sa.Column("tool_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("execution_data", sa.JSON(), nullable=True),
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("chat_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.id"], name="fk_message_flow_steps_chat_id"),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], name="fk_message_flow_steps_message_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_message_flow_steps_id"), "message_flow_steps", ["id"], unique=False)
    op.create_table(
        "message_meta",
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "step_type",
            sa.Enum(
                "INPUT",
                "REWRITE",
                "ROUTER",
                "COMBINATION",
                "SQL_TABLE_SELECTION",
                "SQL_GENERATION",
                "TITLE_GENERATION",
                "TOOL_ORCHESTRATION",
                name="messagemetasteptype",
            ),
            nullable=False,
        ),
        sa.Column("input_text_tokens", sa.Integer(), nullable=True),
        sa.Column("input_text_price", sa.Float(), nullable=True),
        sa.Column("output_text_tokens", sa.Integer(), nullable=True),
        sa.Column("output_text_price", sa.Float(), nullable=True),
        sa.Column("cached_input_text_tokens", sa.Integer(), nullable=True),
        sa.Column("cached_input_text_price", sa.Float(), nullable=True),
        sa.Column("message_id", sa.UUID(), nullable=True),
        sa.Column("llm_model_id", sa.UUID(), nullable=True),
        sa.Column("llm_model_pricing_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["llm_model_id"], ["llm_models.id"], name="fk_message_meta_llm_model_id"),
        sa.ForeignKeyConstraint(["llm_model_pricing_id"], ["llm_model_pricing.id"], name="fk_message_meta_llm_model_pricing_id"),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], name="fk_message_meta_message_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_message_meta_id"), "message_meta", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_message_meta_id"), table_name="message_meta")
    op.drop_table("message_meta")
    op.drop_index(op.f("ix_message_flow_steps_id"), table_name="message_flow_steps")
    op.drop_table("message_flow_steps")
    op.drop_index(op.f("ix_message_feedbacks_user_id"), table_name="message_feedbacks")
    op.drop_index(op.f("ix_message_feedbacks_id"), table_name="message_feedbacks")
    op.drop_table("message_feedbacks")
    op.drop_index(op.f("ix_messages_sequence"), table_name="messages")
    op.drop_index(op.f("ix_messages_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_chat_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_llm_model_pricing_id"), table_name="llm_model_pricing")
    op.drop_table("llm_model_pricing")
    op.drop_index(op.f("ix_llm_models_id"), table_name="llm_models")
    op.drop_table("llm_models")
    op.drop_index(op.f("ix_github_webhooks_id"), table_name="github_webhooks")
    op.drop_table("github_webhooks")
    op.drop_index(op.f("ix_chats_user_id"), table_name="chats")
    op.drop_index(op.f("ix_chats_id"), table_name="chats")
    op.drop_table("chats")
    op.drop_index(op.f("ix_agent_artifacts_id"), table_name="agent_artifacts")
    op.drop_table("agent_artifacts")
    # ### end Alembic commands ###
