from typing import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "43306d5dbfcb"
down_revision: Union[str, None] = "d6b5bf289cd4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_chat_preferences",
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("is_focus_enabled", sa.Boolean(), nullable=False),
        sa.Column("focus_project_id", sa.Uuid(), nullable=True),
        sa.Column("focus_workspace_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("chat_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.id"], name="fk_user_chat_preferences_chat_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_chat_preferences_id"), "user_chat_preferences", ["id"], unique=False)
    op.add_column("chats", sa.Column("is_favorite", sa.Boolean(), server_default=sa.text("false"), nullable=False))
    op.add_column("chats", sa.Column("is_project_chat", sa.Boolean(), server_default=sa.text("false"), nullable=False))
    op.add_column("messages", sa.Column("parsed_content", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "parsed_content")
    op.drop_column("chats", "is_project_chat")
    op.drop_column("chats", "is_favorite")
    op.drop_index(op.f("ix_user_chat_preferences_id"), table_name="user_chat_preferences")
    op.drop_table("user_chat_preferences")
    # ### end Alembic commands ###
