from typing import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "61a53be6c575"
down_revision: Union[str, None] = "1d2e3f4a5b6c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "action_artifact_versions",
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("change_type", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("is_latest", sa.Boolean(), nullable=False),
        sa.Column("is_executed", sa.Boolean(), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("artifact_id", sa.UUID(), nullable=True),
        sa.Column("message_id", sa.UUID(), nullable=True),
        sa.Column("chat_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["artifact_id"], ["action_artifacts.id"], name="fk_action_artifact_versions_artifact_id"),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.id"], name="fk_action_artifact_versions_chat_id"),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], name="fk_action_artifact_versions_message_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_action_artifact_versions_artifact_id"), "action_artifact_versions", ["artifact_id"], unique=False)
    op.create_index(op.f("ix_action_artifact_versions_chat_id"), "action_artifact_versions", ["chat_id"], unique=False)
    op.create_index(op.f("ix_action_artifact_versions_id"), "action_artifact_versions", ["id"], unique=False)
    op.create_index(op.f("ix_action_artifact_versions_message_id"), "action_artifact_versions", ["message_id"], unique=False)
    op.create_index("ix_action_artifact_versions_artifact_executed", "action_artifact_versions", ["artifact_id", "is_executed"], unique=False)
    op.create_index("ix_action_artifact_versions_artifact_version", "action_artifact_versions", ["artifact_id", "version_number"], unique=False)
    op.create_index("ix_action_artifact_versions_unique_version", "action_artifact_versions", ["artifact_id", "version_number"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop essential indexes
    op.drop_index("ix_action_artifact_versions_unique_version", table_name="action_artifact_versions")
    op.drop_index("ix_action_artifact_versions_artifact_version", table_name="action_artifact_versions")
    op.drop_index("ix_action_artifact_versions_artifact_executed", table_name="action_artifact_versions")

    op.drop_index(op.f("ix_action_artifact_versions_message_id"), table_name="action_artifact_versions")
    op.drop_index(op.f("ix_action_artifact_versions_id"), table_name="action_artifact_versions")
    op.drop_index(op.f("ix_action_artifact_versions_chat_id"), table_name="action_artifact_versions")
    op.drop_index(op.f("ix_action_artifact_versions_artifact_id"), table_name="action_artifact_versions")
    op.drop_table("action_artifact_versions")
    # ### end Alembic commands ###
