from typing import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6de9a46f74be"
down_revision: Union[str, None] = "ae536d49945a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message_attachments",
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("original_filename", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column("content_type", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("file_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("file_path", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=True),
        sa.Column("chat_id", sa.Uuid(), nullable=True),
        sa.Column("message_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], name="fk_message_attachments_message_id"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_message_attachments_chat_id"), "message_attachments", ["chat_id"], unique=False)
    op.create_index(op.f("ix_message_attachments_id"), "message_attachments", ["id"], unique=False)
    op.create_index(op.f("ix_message_attachments_message_id"), "message_attachments", ["message_id"], unique=False)
    op.create_index(op.f("ix_message_attachments_user_id"), "message_attachments", ["user_id"], unique=False)
    op.create_index(op.f("ix_message_attachments_workspace_id"), "message_attachments", ["workspace_id"], unique=False)
    op.alter_column("message_feedbacks", "type", existing_type=sa.VARCHAR(length=50), nullable=True)

    op.rename_table("workspacevectorization", "workspace_vectorizations")
    # rename indexes too
    op.execute("ALTER INDEX ix_workspacevectorization_id RENAME TO ix_workspace_vectorizations_id")
    op.execute("ALTER INDEX ix_workspacevectorization_status RENAME TO ix_workspace_vectorizations_status")
    op.execute("ALTER INDEX ix_workspacevectorization_workspace_id RENAME TO ix_workspace_vectorizations_workspace_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("message_feedbacks", "type", existing_type=sa.VARCHAR(length=50), nullable=False)
    op.drop_index(op.f("ix_message_attachments_workspace_id"), table_name="message_attachments")
    op.drop_index(op.f("ix_message_attachments_user_id"), table_name="message_attachments")
    op.drop_index(op.f("ix_message_attachments_message_id"), table_name="message_attachments")
    op.drop_index(op.f("ix_message_attachments_id"), table_name="message_attachments")
    op.drop_index(op.f("ix_message_attachments_chat_id"), table_name="message_attachments")
    op.drop_table("message_attachments")

    op.rename_table("workspace_vectorizations", "workspacevectorization")

    op.execute("ALTER INDEX ix_workspace_vectorizations_id RENAME TO ix_workspacevectorization_id")
    op.execute("ALTER INDEX ix_workspace_vectorizations_status RENAME TO ix_workspacevectorization_status")
    op.execute("ALTER INDEX ix_workspace_vectorizations_workspace_id RENAME TO ix_workspacevectorization_workspace_id")
    # ### end Alembic commands ###
