# SPDX-FileCopyrightText: 2023-present Plane Software, Inc.
# SPDX-License-Identifier: LicenseRef-Plane-Commercial
#
# Licensed under the Plane Commercial License (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# https://plane.so/legals/eula
#
# DO NOT remove or modify this notice.
# NOTICE: Proprietary and confidential. Unauthorized use or distribution is prohibited.

from typing import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d6b5bf289cd4"
down_revision: Union[str, None] = "2a2367c71b4d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workspacevectorization",
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("updated_by_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sa.Enum("queued", "running", "success", "failed", name="vectorizationstatus"), nullable=False),
        sa.Column("feed_issues", sa.Boolean(), nullable=False),
        sa.Column("feed_pages", sa.Boolean(), nullable=False),
        sa.Column("feed_slices", sa.Integer(), nullable=False),
        sa.Column("batch_size", sa.Integer(), nullable=False),
        sa.Column("live_sync_enabled", sa.Boolean(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("progress_pct", sa.Integer(), nullable=False),
        sa.Column("last_error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_workspacevectorization_id"), "workspacevectorization", ["id"], unique=False)
    op.create_index(op.f("ix_workspacevectorization_status"), "workspacevectorization", ["status"], unique=False)
    op.create_index(op.f("ix_workspacevectorization_workspace_id"), "workspacevectorization", ["workspace_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workspacevectorization_workspace_id"), table_name="workspacevectorization")
    op.drop_index(op.f("ix_workspacevectorization_status"), table_name="workspacevectorization")
    op.drop_index(op.f("ix_workspacevectorization_id"), table_name="workspacevectorization")
    op.drop_table("workspacevectorization")
    # ### end Alembic commands ###
