# SPDX-FileCopyrightText: 2023-present Plane Software, Inc.
# SPDX-License-Identifier: LicenseRef-Plane-Commercial
#
# Licensed under the Plane Commercial License (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# https://plane.so/legals/eula
#
# DO NOT remove or modify this notice.
# NOTICE: Proprietary and confidential. Unauthorized use or distribution is prohibited.

from typing import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f0a5b792a8c4"
down_revision: Union[str, None] = "2886eb17eddc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feedbacks",
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("entity_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("usage_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("usage_id", sa.Uuid(), nullable=True),
        sa.Column("feedback", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("feedback_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_feedbacks_id"), "feedbacks", ["id"], unique=False)
    op.create_index(op.f("ix_feedbacks_usage_id"), "feedbacks", ["usage_id"], unique=False)
    op.create_table(
        "page_ai_blocks",
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("block_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("generated_content", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_page_ai_blocks_entity_id"), "page_ai_blocks", ["entity_id"], unique=False)
    op.create_index(op.f("ix_page_ai_blocks_entity_type"), "page_ai_blocks", ["entity_type"], unique=False)
    op.create_index(op.f("ix_page_ai_blocks_id"), "page_ai_blocks", ["id"], unique=False)
    op.create_index(op.f("ix_page_ai_blocks_project_id"), "page_ai_blocks", ["project_id"], unique=False)
    op.create_index(op.f("ix_page_ai_blocks_user_id"), "page_ai_blocks", ["user_id"], unique=False)
    op.create_index(op.f("ix_page_ai_blocks_workspace_id"), "page_ai_blocks", ["workspace_id"], unique=False)
    op.create_table(
        "llm_model_usage_tracking",
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("entity_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("usage_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("usage_id", sa.Uuid(), nullable=True),
        sa.Column("input_text_tokens", sa.Integer(), nullable=True),
        sa.Column("input_text_price", sa.Float(), nullable=True),
        sa.Column("output_text_tokens", sa.Integer(), nullable=True),
        sa.Column("output_text_price", sa.Float(), nullable=True),
        sa.Column("cached_input_text_tokens", sa.Integer(), nullable=True),
        sa.Column("cached_input_text_price", sa.Float(), nullable=True),
        sa.Column("llm_model_id", sa.Uuid(), nullable=True),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["llm_model_id"],
            ["llm_models.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_llm_model_usage_tracking_id"), "llm_model_usage_tracking", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_llm_model_usage_tracking_id"), table_name="llm_model_usage_tracking")
    op.drop_table("llm_model_usage_tracking")
    op.drop_index(op.f("ix_page_ai_blocks_workspace_id"), table_name="page_ai_blocks")
    op.drop_index(op.f("ix_page_ai_blocks_user_id"), table_name="page_ai_blocks")
    op.drop_index(op.f("ix_page_ai_blocks_project_id"), table_name="page_ai_blocks")
    op.drop_index(op.f("ix_page_ai_blocks_id"), table_name="page_ai_blocks")
    op.drop_index(op.f("ix_page_ai_blocks_entity_type"), table_name="page_ai_blocks")
    op.drop_index(op.f("ix_page_ai_blocks_entity_id"), table_name="page_ai_blocks")
    op.drop_table("page_ai_blocks")
    op.drop_index(op.f("ix_feedbacks_id"), table_name="feedbacks")
    op.drop_index(op.f("ix_feedbacks_usage_id"), table_name="feedbacks")
    op.drop_table("feedbacks")
    # ### end Alembic commands ###
