from typing import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f395eac7eb26"
down_revision: Union[str, None] = "6de9a46f74be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "planeoauthstate",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("state", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=True),
        sa.Column("redirect_uri", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("chat_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("message_token", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("return_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_project_chat", sa.Boolean(), nullable=True),
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("pi_sidebar_open", sa.Boolean(), nullable=True),
        sa.Column("sidebar_open_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_used", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_planeoauthstate_state"), "planeoauthstate", ["state"], unique=True)
    op.create_index(op.f("ix_planeoauthstate_user_id"), "planeoauthstate", ["user_id"], unique=False)
    op.create_table(
        "planeoauthtoken",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("workspace_slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("access_token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("refresh_token", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("token_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("expires_in", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("app_installation_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("app_bot_user_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_planeoauthtoken_user_id"), "planeoauthtoken", ["user_id"], unique=False)
    op.create_index(op.f("ix_planeoauthtoken_workspace_id"), "planeoauthtoken", ["workspace_id"], unique=False)
    op.create_index(op.f("ix_planeoauthtoken_workspace_slug"), "planeoauthtoken", ["workspace_slug"], unique=False)
    op.add_column("message_flow_steps", sa.Column("is_executed", sa.Boolean(), server_default=sa.text("false"), nullable=True))
    op.add_column("message_flow_steps", sa.Column("is_planned", sa.Boolean(), server_default=sa.text("false"), nullable=True))
    op.add_column("message_flow_steps", sa.Column("execution_success", sa.String(length=50), nullable=True))
    op.add_column("message_flow_steps", sa.Column("execution_error", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column("message_flow_steps", sa.Column("oauth_required", sa.Boolean(), server_default=sa.text("false"), nullable=True))
    op.add_column("message_flow_steps", sa.Column("oauth_completed", sa.Boolean(), server_default=sa.text("false"), nullable=True))
    op.add_column("message_flow_steps", sa.Column("oauth_completed_at", sa.DateTime(), nullable=True))
    op.create_index(op.f("ix_message_flow_steps_execution_success"), "message_flow_steps", ["execution_success"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_message_flow_steps_execution_success"), table_name="message_flow_steps")
    op.drop_column("message_flow_steps", "oauth_completed_at")
    op.drop_column("message_flow_steps", "oauth_completed")
    op.drop_column("message_flow_steps", "oauth_required")
    op.drop_column("message_flow_steps", "execution_error")
    op.drop_column("message_flow_steps", "execution_success")
    op.drop_column("message_flow_steps", "is_planned")
    op.drop_column("message_flow_steps", "is_executed")
    op.drop_index(op.f("ix_planeoauthtoken_workspace_slug"), table_name="planeoauthtoken")
    op.drop_index(op.f("ix_planeoauthtoken_workspace_id"), table_name="planeoauthtoken")
    op.drop_index(op.f("ix_planeoauthtoken_user_id"), table_name="planeoauthtoken")
    op.drop_table("planeoauthtoken")
    op.drop_index(op.f("ix_planeoauthstate_user_id"), table_name="planeoauthstate")
    op.drop_index(op.f("ix_planeoauthstate_state"), table_name="planeoauthstate")
    op.drop_table("planeoauthstate")
    # ### end Alembic commands ###
