# Generated by Django 4.2.22 on 2025-10-30 10:52

from django.db import migrations
from django.utils import timezone

def publish_marketplace_apps(apps, schema_editor):
  from plane.silo.utils.constants import APPLICATIONS
  Application = apps.get_model("authentication", "Application")
  marketplace_apps_slugs = [
    APPLICATIONS["github_enterprise"]["slug"],
    APPLICATIONS["github"]["slug"],
    APPLICATIONS["gitlab_enterprise"]["slug"],
    APPLICATIONS["gitlab"]["slug"],
    APPLICATIONS["slack"]["slug"],
    APPLICATIONS["sentry"]["slug"],
    APPLICATIONS["drawio"]["slug"],
  ]
  marketplace_apps = Application.objects.filter(slug__in=marketplace_apps_slugs)
  for app in marketplace_apps:
    if app.published_at is None:
      app.published_at = timezone.now()
      app.status = "published"
      app.save()
      print(f"Published app {app.slug}")
    else:
      print(f"App {app.slug} already published skipping")


class Migration(migrations.Migration):

    dependencies = [
        ('silo', '0008_create_drawio_app'),
    ]

    operations = [
      migrations.RunPython(publish_marketplace_apps, reverse_code=migrations.RunPython.noop),
    ]
